package cloud.yelynn.envmanager.util;

import cloud.yelynn.envmanager.model.EnvironmentVariable;
import cloud.yelynn.envmanager.model.EnvironmentVariableSet;
import com.intellij.openapi.diagnostic.Logger;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.List;

/**
 * Utility class for exporting environment variables to text files.
 */
public class TextFileExporter {
    private static final Logger LOG = Logger.getInstance(TextFileExporter.class);

    /**
     * Exports environment variables from a set to a text file.
     * Format: KEY=VALUE (one per line)
     *
     * @param set The environment variable set to export
     * @param file The text file to export to
     * @return true if export was successful, false otherwise
     */
    public static boolean exportToFile(EnvironmentVariableSet set, File file) {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(file))) {
            // Write a header comment
            writer.write("# Environment variables exported from set: " + set.getName());
            writer.newLine();
            writer.write("# Generated by Environment Manager plugin");
            writer.newLine();
            writer.newLine();
            
            // Write each variable
            List<EnvironmentVariable> variables = set.getVariables();
            for (EnvironmentVariable variable : variables) {
                writer.write(variable.getKey() + "=" + variable.getValue());
                writer.newLine();
            }
            
            return true;
        } catch (IOException e) {
            LOG.error("Error writing environment file: " + file.getPath(), e);
            return false;
        }
    }
}